import * as fs from "fs";
import * as path from "path";

async function main() {
  // Read the ABI from the abis folder
  const abiPath = path.join(__dirname, "../abis/Betflix.json");
  const abi = JSON.parse(fs.readFileSync(abiPath, "utf8"));

  // Get the deployed contract address from environment variable
  const contractAddress = "0xc451425db45500b73a9D5C6E1f5F8a7A4BDb5229";

  if (!contractAddress) {
    throw new Error("BETFLIX_CONTRACT_ADDRESS environment variable not set");
  }

  // Create the deployedContracts object for Sepolia only
  const deployedContracts = {
    11155111: {
      Betflix: {
        address: contractAddress,
        abi: abi,
      },
    },
  };

  // Write to deployedContracts.ts
  const deployedContractsPath = path.join(__dirname, "../../nextjs/contracts/deployedContracts.ts");
  const content = `/**
 * This file is autogenerated by scripts/updateDeployedContracts.ts.
 * You should not edit it manually.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = ${JSON.stringify(deployedContracts, null, 2)} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
`;

  fs.writeFileSync(deployedContractsPath, content);
  console.log("✅ Updated deployedContracts.ts with Sepolia deployment");
  console.log(`Contract address: ${contractAddress}`);
}

main().catch(error => {
  console.error(error);
  process.exitCode = 1;
});
